// src/lib/permissions.ts

export const PERMISSIONS = {
  // User Management
  CAN_VIEW_USERS: 'CAN_VIEW_USERS',
  CAN_CREATE_USERS: 'CAN_CREATE_USERS',
  CAN_EDIT_USERS: 'CAN_EDIT_USERS',
  CAN_DELETE_USERS: 'CAN_DELETE_USERS',

  // Role Management
  CAN_VIEW_ROLES: 'CAN_VIEW_ROLES',
  CAN_CREATE_ROLES: 'CAN_CREATE_ROLES',
  CAN_EDIT_ROLES: 'CAN_EDIT_ROLES',
  CAN_DELETE_ROLES: 'CAN_DELETE_ROLES',

  // Catalog Management
  CAN_VIEW_CATALOG: 'CAN_VIEW_CATALOG',
  CAN_CREATE_PRODUCTS: 'CAN_CREATE_PRODUCTS',
  CAN_EDIT_PRODUCTS: 'CAN_EDIT_PRODUCTS',
  CAN_DELETE_PRODUCTS: 'CAN_DELETE_PRODUCTS',

  // Inventory Management
  CAN_VIEW_INVENTORY: 'CAN_VIEW_INVENTORY',
  CAN_CREATE_INVENTORY: 'CAN_CREATE_INVENTORY',
  CAN_EDIT_INVENTORY: 'CAN_EDIT_INVENTORY',
  CAN_DELETE_INVENTORY: 'CAN_DELETE_INVENTORY',

  // Delivery Ticket Management
  CAN_VIEW_DELIVERY_TICKETS: 'CAN_VIEW_DELIVERY_TICKETS',
  CAN_CREATE_DELIVERY_TICKETS: 'CAN_CREATE_DELIVERY_TICKETS',
  CAN_EDIT_DELIVERY_TICKETS: 'CAN_EDIT_DELIVERY_TICKETS',
  CAN_DELETE_DELIVERY_TICKETS: 'CAN_DELETE_DELIVERY_TICKETS',

  // Return Ticket Management
  CAN_VIEW_RETURN_TICKETS: 'CAN_VIEW_RETURN_TICKETS',
  CAN_CREATE_RETURN_TICKETS: 'CAN_CREATE_RETURN_TICKETS',
  CAN_EDIT_RETURN_TICKETS: 'CAN_EDIT_RETURN_TICKETS',
  CAN_DELETE_RETURN_TICKETS: 'CAN_DELETE_RETURN_TICKETS',

  // Vendor Management
  CAN_VIEW_VENDORS: 'CAN_VIEW_VENDORS',
  CAN_CREATE_VENDORS: 'CAN_CREATE_VENDORS',
  CAN_EDIT_VENDORS: 'CAN_EDIT_VENDORS',
  CAN_DELETE_VENDORS: 'CAN_DELETE_VENDORS',

  // Customer Management
  CAN_VIEW_CUSTOMERS: 'CAN_VIEW_CUSTOMERS',
  CAN_CREATE_CUSTOMERS: 'CAN_CREATE_CUSTOMERS',
  CAN_EDIT_CUSTOMERS: 'CAN_EDIT_CUSTOMERS',
  CAN_DELETE_CUSTOMERS: 'CAN_DELETE_CUSTOMERS',

  // Dashboard Access
  CAN_VIEW_DASHBOARD: 'CAN_VIEW_DASHBOARD',

  // Raw Materials
  CAN_VIEW_RAW_MATERIALS: 'CAN_VIEW_RAW_MATERIALS',
  CAN_CREATE_RAW_MATERIALS: 'CAN_CREATE_RAW_MATERIALS',
  CAN_EDIT_RAW_MATERIALS: 'CAN_EDIT_RAW_MATERIALS',
  CAN_DELETE_RAW_MATERIALS: 'CAN_DELETE_RAW_MATERIALS',
};

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Map roles to their permissions
export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  Admin: [
    PERMISSIONS.CAN_VIEW_USERS,
    PERMISSIONS.CAN_CREATE_USERS,
    PERMISSIONS.CAN_EDIT_USERS,
    PERMISSIONS.CAN_DELETE_USERS,
    PERMISSIONS.CAN_VIEW_ROLES,
    PERMISSIONS.CAN_CREATE_ROLES,
    PERMISSIONS.CAN_EDIT_ROLES,
    PERMISSIONS.CAN_DELETE_ROLES,
    PERMISSIONS.CAN_VIEW_CATALOG,
    PERMISSIONS.CAN_CREATE_PRODUCTS,
    PERMISSIONS.CAN_EDIT_PRODUCTS,
    PERMISSIONS.CAN_DELETE_PRODUCTS,
    PERMISSIONS.CAN_VIEW_INVENTORY,
    PERMISSIONS.CAN_CREATE_INVENTORY,
    PERMISSIONS.CAN_EDIT_INVENTORY,
    PERMISSIONS.CAN_DELETE_INVENTORY,
    PERMISSIONS.CAN_VIEW_DELIVERY_TICKETS,
    PERMISSIONS.CAN_CREATE_DELIVERY_TICKETS,
    PERMISSIONS.CAN_EDIT_DELIVERY_TICKETS,
    PERMISSIONS.CAN_DELETE_DELIVERY_TICKETS,
    PERMISSIONS.CAN_VIEW_RETURN_TICKETS,
    PERMISSIONS.CAN_CREATE_RETURN_TICKETS,
    PERMISSIONS.CAN_EDIT_RETURN_TICKETS,
    PERMISSIONS.CAN_DELETE_RETURN_TICKETS,
    PERMISSIONS.CAN_VIEW_VENDORS,
    PERMISSIONS.CAN_CREATE_VENDORS,
    PERMISSIONS.CAN_EDIT_VENDORS,
    PERMISSIONS.CAN_DELETE_VENDORS,
    PERMISSIONS.CAN_VIEW_CUSTOMERS,
    PERMISSIONS.CAN_CREATE_CUSTOMERS,
    PERMISSIONS.CAN_EDIT_CUSTOMERS,
    PERMISSIONS.CAN_DELETE_CUSTOMERS,
    PERMISSIONS.CAN_VIEW_DASHBOARD,
  ],
  Manager: [
    PERMISSIONS.CAN_VIEW_USERS,
    PERMISSIONS.CAN_VIEW_ROLES,
    PERMISSIONS.CAN_VIEW_CATALOG,
    PERMISSIONS.CAN_CREATE_PRODUCTS,
    PERMISSIONS.CAN_EDIT_PRODUCTS,
    PERMISSIONS.CAN_VIEW_INVENTORY,
    PERMISSIONS.CAN_CREATE_INVENTORY,
    PERMISSIONS.CAN_EDIT_INVENTORY,
    PERMISSIONS.CAN_VIEW_DELIVERY_TICKETS,
    PERMISSIONS.CAN_CREATE_DELIVERY_TICKETS,
    PERMISSIONS.CAN_EDIT_DELIVERY_TICKETS,
    PERMISSIONS.CAN_VIEW_RETURN_TICKETS,
    PERMISSIONS.CAN_CREATE_RETURN_TICKETS,
    PERMISSIONS.CAN_EDIT_RETURN_TICKETS,
    PERMISSIONS.CAN_VIEW_VENDORS,
    PERMISSIONS.CAN_CREATE_VENDORS,
    PERMISSIONS.CAN_EDIT_VENDORS,
    PERMISSIONS.CAN_VIEW_CUSTOMERS,
    PERMISSIONS.CAN_CREATE_CUSTOMERS,
    PERMISSIONS.CAN_EDIT_CUSTOMERS,
    PERMISSIONS.CAN_VIEW_DASHBOARD,
  ],
  User: [
    PERMISSIONS.CAN_VIEW_CATALOG,
    PERMISSIONS.CAN_VIEW_INVENTORY,
    PERMISSIONS.CAN_VIEW_DELIVERY_TICKETS,
    PERMISSIONS.CAN_VIEW_RETURN_TICKETS,
    PERMISSIONS.CAN_VIEW_VENDORS,
    PERMISSIONS.CAN_VIEW_CUSTOMERS,
    PERMISSIONS.CAN_VIEW_DASHBOARD,
  ],
  // Add other roles as needed
};
